package com.ktb.hackathon.team11.task;
import com.ktb.hackathon.team11.ai.*;import com.ktb.hackathon.team11.global.response.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import lombok.RequiredArgsConstructor;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.*;
@RestController @RequestMapping("/api/v1") @RequiredArgsConstructor
public class TaskTemplateController{private final TaskTemplateService service;
@PostMapping("/groups/{groupId}/task-drafts")ApiResponse<TaskTemplateService.DraftResponse> draft(@PathVariable long groupId,@Valid @RequestBody DraftRequest r){return ApiResponse.of("TASK_DRAFT_CREATED",service.draft(groupId,r.managerId(),r.message()));}
@PostMapping("/groups/{groupId}/task-templates")@ResponseStatus(HttpStatus.CREATED)ApiResponse<TemplateResponse> create(@PathVariable long groupId,@Valid @RequestBody CreateTemplateRequest r){TaskTemplate t=service.create(groupId,r.managerId(),r.title(),r.sourceMessage(),r.items().stream().map(i->new TaskTemplateService.ItemCommand(i.title(),i.instruction(),i.completionType(),i.verificationRule())).toList());return ApiResponse.of("TASK_TEMPLATE_CREATED",TemplateResponse.from(t,service.items(t.getId())));}
@GetMapping("/groups/{groupId}/task-templates")ApiResponse<List<TemplateResponse>> list(@PathVariable long groupId,@RequestParam long memberId){return ApiResponse.of("TASK_TEMPLATES_FOUND",service.list(groupId,memberId).stream().map(t->TemplateResponse.from(t,service.items(t.getId()))).toList());}
@GetMapping("/task-templates/{id}")ApiResponse<TemplateResponse> detail(@PathVariable long id,@RequestParam long memberId){TaskTemplate t=service.require(id);service.list(t.getGroup().getId(),memberId);return ApiResponse.of("TASK_TEMPLATE_FOUND",TemplateResponse.from(t,service.items(id)));}
@PatchMapping("/task-templates/{id}")ApiResponse<TemplateResponse> update(@PathVariable long id,@Valid @RequestBody UpdateTemplateRequest r){TaskTemplate t=service.update(id,r.managerId(),r.title(),r.active());return ApiResponse.of("TASK_TEMPLATE_UPDATED",TemplateResponse.from(t,service.items(id)));}
@PostMapping(value="/task-items/{itemId}/reference-image",consumes="multipart/form-data")ApiResponse<String> reference(@PathVariable long itemId,@RequestParam long managerId,@RequestPart MultipartFile photo){return ApiResponse.of("REFERENCE_IMAGE_SAVED",service.addReferenceImage(itemId,managerId,photo));}
@DeleteMapping("/task-templates/{id}")ApiResponse<Void> delete(@PathVariable long id,@RequestParam long managerId){service.deactivate(id,managerId);return ApiResponse.of("TASK_TEMPLATE_DEACTIVATED",null);}
public record DraftRequest(@NotNull Long managerId,@NotBlank @Size(max=2000)String message){}public record ItemRequest(@NotBlank @Size(max=80)String title,@NotBlank @Size(max=500)String instruction,@NotNull CompletionType completionType,@Size(max=1000)String verificationRule){}public record CreateTemplateRequest(@NotNull Long managerId,@NotBlank @Size(max=80)String title,@NotBlank @Size(max=2000)String sourceMessage,@NotEmpty @Size(max=20)List<@Valid ItemRequest> items){}
public record UpdateTemplateRequest(@NotNull Long managerId,@Size(max=80)String title,Boolean active){}
public record ItemResponse(Long itemId,int sequence,String title,String instruction,CompletionType completionType,String verificationRule){static ItemResponse from(TaskItemTemplate i){return new ItemResponse(i.getId(),i.getSequence(),i.getTitle(),i.getInstruction(),i.getCompletionType(),i.getVerificationRule());}}public record TemplateResponse(Long templateId,Long groupId,String title,boolean active,List<ItemResponse> items){static TemplateResponse from(TaskTemplate t,List<TaskItemTemplate> i){return new TemplateResponse(t.getId(),t.getGroup().getId(),t.getTitle(),t.isActive(),i.stream().map(ItemResponse::from).toList());}}
}
