package com.ktb.hackathon.team11.schedule;
import com.ktb.hackathon.team11.assignment.*;import com.ktb.hackathon.team11.global.exception.*;import com.ktb.hackathon.team11.group.GroupService;import com.ktb.hackathon.team11.member.*;import com.ktb.hackathon.team11.task.*;import lombok.RequiredArgsConstructor;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor
public class ScheduleService{private final TaskScheduleRepository schedules;private final TaskAssignmentRepository assignments;private final TaskTemplateService templates;private final MemberService members;private final GroupService groups;private final TaskItemTemplateRepository items;private final Clock clock;
@Transactional public TaskSchedule create(long templateId,long managerId,Long assigneeId,LocalDate sd,LocalDate ed,LocalTime st,LocalTime et,RecurrenceType rt,Set<DayOfWeek> days,int early,int late){TaskTemplate t=templates.require(templateId);groups.requireManager(t.getGroup().getId(),managerId);Member a=null;if(assigneeId!=null){a=members.requireRole(assigneeId,MemberRole.WORKER);groups.requireMember(t.getGroup().getId(),assigneeId);}return schedules.save(new TaskSchedule(t,a,sd,ed,st,et,rt,days,early,late));}
@Transactional public int generate(long groupId,long managerId,LocalDate date){groups.requireManager(groupId,managerId);return generateGroup(groupId,date);}
private int generateGroup(long groupId,LocalDate date){List<TaskSchedule> all=new ArrayList<>(schedules.findAllByActiveTrueAndStartDateLessThanEqualAndEndDateGreaterThanEqual(date,date));all.addAll(schedules.findAllByActiveTrueAndStartDateLessThanEqualAndEndDateIsNull(date));int count=0;for(TaskSchedule s:all)if(s.getTaskTemplate().getGroup().getId().equals(groupId)&&s.occursOn(date)){TaskSchedule.Window w=s.windowFor(date);for(TaskItemTemplate i:items.findAllByTaskTemplateIdOrderBySequence(s.getTaskTemplate().getId()))if(!assignments.existsByScheduleIdAndTaskItemTemplateIdAndScheduledDate(s.getId(),i.getId(),date)){assignments.save(new TaskAssignment(s,i,date,w.availableFrom(),w.dueAt()));count++;}}return count;}
@Scheduled(cron="${task.assignment-generation-cron:0 0 0 * * *}",zone="Asia/Seoul")@Transactional public void generateTomorrow(){LocalDate d=LocalDate.now(clock).plusDays(1);for(TaskSchedule s:schedules.findAll())if(s.isActive())generateGroup(s.getTaskTemplate().getGroup().getId(),d);}
}
